// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zrW8g0Hm5UFA_RfbNIof-Wupnm1PClQ',
    appId: '1:891643218418:web:ab86ec579678df206e836b',
    messagingSenderId: '891643218418',
    projectId: 'carcare-66629',
    authDomain: 'carcare-66629.firebaseapp.com',
    storageBucket: 'carcare-66629.firebasestorage.app',
    measurementId: 'G-9CNX3XZ276',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_3As4OPQuMN-K-qiUY-4hmgtU8ku-7pg',
    appId: '1:891643218418:android:f82eacf6a747cf7d6e836b',
    messagingSenderId: '891643218418',
    projectId: 'carcare-66629',
    storageBucket: 'carcare-66629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxH_C9zgEs2rsaMuEkzMFo3jhGyAqRMss',
    appId: '1:891643218418:ios:388f445a04b5030e6e836b',
    messagingSenderId: '891643218418',
    projectId: 'carcare-66629',
    storageBucket: 'carcare-66629.firebasestorage.app',
    iosBundleId: 'com.example.carcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxH_C9zgEs2rsaMuEkzMFo3jhGyAqRMss',
    appId: '1:891643218418:ios:388f445a04b5030e6e836b',
    messagingSenderId: '891643218418',
    projectId: 'carcare-66629',
    storageBucket: 'carcare-66629.firebasestorage.app',
    iosBundleId: 'com.example.carcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7zrW8g0Hm5UFA_RfbNIof-Wupnm1PClQ',
    appId: '1:891643218418:web:8ce2020c151e3de16e836b',
    messagingSenderId: '891643218418',
    projectId: 'carcare-66629',
    authDomain: 'carcare-66629.firebaseapp.com',
    storageBucket: 'carcare-66629.firebasestorage.app',
    measurementId: 'G-J8NCEWQN79',
  );
}
